### ISSUE TITLE
The example from the README.md doesn't work

### ISSUE THREAD

**Issue by bguban** [ivamuno/redoc-asyncapi#10]
I try to run the example from the example https://github.com/ivamuno/redoc-asyncapi#tldr but it doesn't work and I see 
```
url.js:25 Uncaught TypeError: Cannot read properties of undefined (reading 'parse')
    at 9185 (url.js:25:1)
    at r (bootstrap:19:32)
    at 9566 (pointer.js:6:13)
    at r (bootstrap:19:32)
    at 1969 (ref.js:5:17)
    at r (bootstrap:19:32)
    at 1922 (refs.js:4:14)
    at r (bootstrap:19:32)
    at 321 (index.js:4:15)
    at r (bootstrap:19:32)
```
in the console. I also tried other URLs but it still doesn't work

**Comment by mkraszew** [comment]
Hi,

I have the same issue. In version redoc-asyncapi/0.4.0 it was working fine. With the newest one 2.1.1 it doesn't work.
